// Pay Index basket versioning — single source of truth for the version
// numbers that gate every basket change.
//
// The basket (job titles + cities in jobs.ts / cities.ts) may ONLY change via
// a bump to BASKET_VERSION accompanied by a dated entry in changelog.ts. This
// is not just a convention: tests/payindex/fingerprint.test.ts recomputes
// BASKET_FINGERPRINT from the live jobs.ts/cities.ts data and fails the suite
// if it no longer matches this checked-in value — so an edit to the basket
// without a version bump breaks the build, not just the docs.
//
// BASKET_FINGERPRINT was generated by
// netlify/functions/_lib/payindex/fingerprint.ts#computeBasketFingerprint
// against the jobs/cities data at BASKET_VERSION 'v1'. Regenerate it with:
//   npx tsx -e "
//     import('./netlify/functions/_lib/payindex/fingerprint.ts').then(async ({ computeBasketFingerprint }) => {
//       const { jobs } = await import('./src/data/payIndex/jobs.ts')
//       const { cities } = await import('./src/data/payIndex/cities.ts')
//       console.log(computeBasketFingerprint(jobs, cities))
//     })
//   "

export const BASKET_VERSION = 'v1'
export const METHODOLOGY_VERSION = 'v1'

// Date the current basket version took effect. Must match the most recent
// changelog.ts entry's effectiveDate for this BASKET_VERSION.
export const BASKET_EFFECTIVE_DATE = '2026-08-06'

// A (job x city) cell needs at least this many raw observations in a period
// to be included in the index calculation. Below this, the cell is an
// explicit, published gap — never interpolated, never carried forward.
export const MIN_OBSERVATIONS = 5

// Hours used to annualize an hourly wage for the normalized figure. The raw
// original (hourly or annual, whichever the source reported) is always kept
// alongside the normalized value — normalization never replaces raw data.
export const ANNUALIZATION_HOURS = 2080

// Checked-in fingerprint of the jobs.ts + cities.ts basket at this version.
// See the regeneration command in the header comment above.
export const BASKET_FINGERPRINT = 'fa03ed9485e66c84'

// The literal formula text published alongside every headline number
// (methodology rule 6 — full traceability). Keep this in sync with what
// netlify/functions/_lib/payindex/computeIndex.ts actually does.
export const FORMULA_TEXT =
  'For every (job x city) cell with at least ' +
  MIN_OBSERVATIONS +
  ' raw observations in both the current and baseline period, % change = ' +
  '(current cell median - baseline cell median) / baseline cell median. ' +
  'The headline is the simple, unweighted arithmetic mean of every included ' +
  "cell's % change. No weighting by employment share, population, or " +
  'posting volume. The median of the same % changes is shown alongside the ' +
  'mean for comparison, but the mean is the headline. Cells below the ' +
  'observation threshold are excluded and counted as coverage gaps, never ' +
  'interpolated or substituted.'
